# Generated by Django 4.0.4 on 2022-05-10 07:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_status_alter_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(help_text='正文必须为MarkDown格式', verbose_name='正文'),
        ),
    ]
